#Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]],np.int8)

In [3]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [4]:
myarr[0]

array([ 3,  6, 32,  7], dtype=int8)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr[0,1]

6

In [8]:
myarr[0,1]= 45

#Array creation : Conversion from other Python structures

In [9]:
import numpy as np

In [10]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({34, 54, 65})

array({65, 34, 54}, dtype=object)

In [16]:
zeros = np.zeros((2, 5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.size

10

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(1,56, 4)

In [22]:
lspace

array([ 1.        , 19.33333333, 37.66666667, 56.        ])

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        6.89805151e-307, 1.78020169e-306, 1.42410974e-306]])

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([ 1.        , 19.33333333, 37.66666667, 56.        ])

In [27]:
ide = np.identity(45)

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
 x = [[1,2,3],[4,5,6],[7,1, 0]]

In [35]:
ar = np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar.sum(axis = 0)

array([12,  8,  9])

In [38]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [40]:
ar.flat

In [41]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [42]:
ar.ndim

2

In [43]:
ar.size

9

In [44]:
ar.nbytes

36

In [45]:
one = np.array([1,3,4,634,2])

In [46]:
one

array([  1,   3,   4, 634,   2])

In [47]:
one.argmax()

3

In [48]:
one.argmin()

0

In [49]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [50]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [51]:
ar.argmin()

8

In [52]:
ar.argmax()

6

In [53]:
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [54]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [55]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [56]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [62]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [63]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [64]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [65]:
ar - ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [67]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [68]:
ar.sum()

29

In [69]:
ar.max()

7

In [70]:
ar.min()

0

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [73]:
type(np.where(ar>5))

tuple

In [74]:
np.count_nonzero(ar)

8

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [76]:
ar[1,2] = 0

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [79]:
type(np.nonzero(ar))

tuple

In [80]:
import sys

In [81]:
py_ar = [0,4,55,2]

In [82]:
np_ar = np.array(py_ar)

In [83]:
sys.getsizeof(1) * len(py_ar)

112

In [84]:
np_ar.itemsize * np_ar.size

16

In [85]:
'''numpy methods and attributes'''
'''scipy.org'''

'scipy.org'